name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
description: ${project.description}

# Ask Bukkit to load our plugin before CommandBook or Essentials, to ensure our plugin registers its commands first.
loadbefore: [CommandBook, Essentials]

database: true

commands:
    ib:
        description: Allows access to core ${project.name} functions.
        usage: /ib reload
    ban:
        description: Bans a player from the server.
        usage: /ban <player> <time> <reason>
    unban:
        description: Unbans a player from the server.
        usage: /unban <player> <reason>
    kick:
        description: Kicks a player from the server.
        usage: /kick <player> <reason>
    rap:
        description: Displays a user's "rap sheet", showing their kick/ban history.
        usage: /rap <player>